[package]
name = "cli_read"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli_shared = {path = "../cli_shared"}
clap = { version = "4.0", features = ["derive"] }